// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DailyActivity {
  final String date;
  final int count;

  const DailyActivity({required this.date, required this.count});

  @override
  int get hashCode => date.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyActivity &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          count == other.count;
}

class DailyTokenUsage {
  final String date;
  final int inputTokens;
  final int outputTokens;
  final int cachedTokens;
  final int totalTokens;

  const DailyTokenUsage({
    required this.date,
    required this.inputTokens,
    required this.outputTokens,
    required this.cachedTokens,
    required this.totalTokens,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      cachedTokens.hashCode ^
      totalTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyTokenUsage &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          cachedTokens == other.cachedTokens &&
          totalTokens == other.totalTokens;
}

class ProviderTokenUsage {
  final String date;
  final String providerName;
  final String modelId;
  final int tokens;

  const ProviderTokenUsage({
    required this.date,
    required this.providerName,
    required this.modelId,
    required this.tokens,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      providerName.hashCode ^
      modelId.hashCode ^
      tokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderTokenUsage &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          providerName == other.providerName &&
          modelId == other.modelId &&
          tokens == other.tokens;
}

class StatsSnapshot {
  final StatsSummary summary;
  final List<DailyActivity> activity;
  final List<DailyTokenUsage> tokenUsage;
  final List<ProviderTokenUsage> providerUsage;

  const StatsSnapshot({
    required this.summary,
    required this.activity,
    required this.tokenUsage,
    required this.providerUsage,
  });

  @override
  int get hashCode =>
      summary.hashCode ^
      activity.hashCode ^
      tokenUsage.hashCode ^
      providerUsage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsSnapshot &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          activity == other.activity &&
          tokenUsage == other.tokenUsage &&
          providerUsage == other.providerUsage;
}

class StatsSummary {
  final int summaries;
  final int fimCompletions;
  final int totalRecords;
  final int dailyNotes;
  final int weeklyNotes;
  final int monthlyNotes;
  final int inputTokens;
  final int outputTokens;
  final int cachedTokens;
  final int appLaunches;
  final int workSeconds;
  final double coins;

  const StatsSummary({
    required this.summaries,
    required this.fimCompletions,
    required this.totalRecords,
    required this.dailyNotes,
    required this.weeklyNotes,
    required this.monthlyNotes,
    required this.inputTokens,
    required this.outputTokens,
    required this.cachedTokens,
    required this.appLaunches,
    required this.workSeconds,
    required this.coins,
  });

  @override
  int get hashCode =>
      summaries.hashCode ^
      fimCompletions.hashCode ^
      totalRecords.hashCode ^
      dailyNotes.hashCode ^
      weeklyNotes.hashCode ^
      monthlyNotes.hashCode ^
      inputTokens.hashCode ^
      outputTokens.hashCode ^
      cachedTokens.hashCode ^
      appLaunches.hashCode ^
      workSeconds.hashCode ^
      coins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatsSummary &&
          runtimeType == other.runtimeType &&
          summaries == other.summaries &&
          fimCompletions == other.fimCompletions &&
          totalRecords == other.totalRecords &&
          dailyNotes == other.dailyNotes &&
          weeklyNotes == other.weeklyNotes &&
          monthlyNotes == other.monthlyNotes &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          cachedTokens == other.cachedTokens &&
          appLaunches == other.appLaunches &&
          workSeconds == other.workSeconds &&
          coins == other.coins;
}
